### PR TITLE
Deploying service to AWS Lamba

### PR DESCRIPTION
**Pull request by cbrzn**

### CODE REVIEW

**Comment by dOrgJelli** [comment]
Looks great @cbrzn. Now that a "secrets.json" file is being used, should we update the README instructions?

**Comment by cbrzn** [comment]
Yas! I was wondering if we should remove the netlify stuff since it wont work because of the timeout, or what do you think? @dOrgJelli 

Btw, the service is deployed right now with my personal account, I think we should move this to the organization's account so we all have access to it

**Comment by dOrgJelli** [comment]
Yes we should remove Netlify. Also do we need one running right now? Isn't this just for testing.

**Comment by cbrzn** [comment]
I would say that, if this service is going to be used on ETHDenver, then we should start with the set up

**Pull request merged**
